### ISSUE TITLE
Remove secrets from settings.py

### ISSUE THREAD

**Issue by brejoc** [JonPizza/jon-network-source#2]
Please remove all of the secrets from the settings.py and invalidate or change them. You are risking to be hacked!

**Comment by abhiTronix** [comment]
:fearful: This is serious, his google password is out in the open.

**Comment by brejoc** [comment]
@JonPizza I'd suggest you look into ["The Twelve Factor App"](https://12factor.net/). You can use [django-environ](https://pypi.org/project/django-environ/) for this pretty easily.

**Comment by AmiyKumar** [comment]
@JonPizza Even after removing passwords they are still in
[commit history](https://github.com/JonPizza/jon-network-source/commit/348ee67a87494290e3d3583f7068ca35ee603350), store them as environment variables.

**Comment by JonPizza** [comment]
Yeah... when I was setting this up I didn't know what an env variable was... at this point there is nothing left of value, everything has been changed by me. (including some twitter api keys...)

**Comment by brejoc** [comment]
I hope nothing bad happened. And I guess this is a lesson you won’t ever forget. So there is also something good to it. 😉
I’m closing this issue since you mentioned that you changed all of the passwords and secrets.

**Comment by JonPizza** [comment]
Can I just change the secret key w/o it mattering? I'm it testing now
